// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IntegrationRequest integration request
//
// swagger:model IntegrationRequest
type IntegrationRequest struct {

	// name
	// Example: deploy
	Name string `json:"name,omitempty"`

	// project id
	ProjectID int64 `json:"project_id,omitempty"`

	// template id
	TemplateID int64 `json:"template_id,omitempty"`

	// searchable
	Searchable bool `json:"searchable,omitempty"`

	// auth method
	// Enum: ["token","github","bitbucket","hmac","basic"]
	AuthMethod string `json:"auth_method,omitempty"`

	// auth secret id
	AuthSecretID int64 `json:"auth_secret_id,omitempty"`

	// auth header
	AuthHeader string `json:"auth_header,omitempty"`
}

// Validate validates this integration request
func (m *IntegrationRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this integration request based on context it is used
func (m *IntegrationRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IntegrationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IntegrationRequest) UnmarshalBinary(b []byte) error {
	var res IntegrationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
