// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Integration integration
//
// swagger:model Integration
type Integration struct {

	// id
	ID int64 `json:"id,omitempty"`

	// name
	// Example: deploy
	Name string `json:"name,omitempty"`

	// project id
	// Minimum: 1
	ProjectID int64 `json:"project_id,omitempty"`

	// template id
	// Minimum: 1
	TemplateID int64 `json:"template_id,omitempty"`

	// searchable
	Searchable bool `json:"searchable,omitempty"`

	// auth method
	// Enum: ["token","github","bitbucket","hmac","basic"]
	AuthMethod string `json:"auth_method,omitempty"`

	// auth secret id
	AuthSecretID int64 `json:"auth_secret_id,omitempty"`

	// auth header
	AuthHeader string `json:"auth_header,omitempty"`
}

// Validate validates this integration
func (m *Integration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTemplateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Integration) validateProjectID(formats strfmt.Registry) error {
	if swag.IsZero(m.ProjectID) { // not required
		return nil
	}

	if err := validate.MinimumInt("project_id", "body", m.ProjectID, 1, false); err != nil {
		return err
	}

	return nil
}

func (m *Integration) validateTemplateID(formats strfmt.Registry) error {
	if swag.IsZero(m.TemplateID) { // not required
		return nil
	}

	if err := validate.MinimumInt("template_id", "body", m.TemplateID, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this integration based on context it is used
func (m *Integration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Integration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Integration) UnmarshalBinary(b []byte) error {
	var res Integration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
